param([Parameter(Mandatory=$true)][string]$InstDir)
# ZhiShi installer: drop zhishi CLI into ~/.zhishi/bin and register it on the
# user PATH (HKCU). ASCII-only file (PowerShell 5.1 reads UTF-8 without BOM as ANSI).
# The generated zhishi.cmd content must stay byte-identical with
# src-tauri/src/cli_launcher.rs cli_cmd_content() — the launcher re-mirrors on
# every launch and content-compares, so any drift causes a one-time rewrite.
$ErrorActionPreference = 'Stop'

$bin = Join-Path $env:USERPROFILE '.zhishi\bin'
New-Item -ItemType Directory -Force $bin | Out-Null

# Tauri NSIS 的资源在 Windows 上落在安装根目录（不是 resources\ 子目录）。
Copy-Item (Join-Path $InstDir 'cli\zhishi.js') (Join-Path $bin 'zhishi') -Force
Copy-Item (Join-Path $InstDir 'cli\package.json') $bin -Force

$node = Join-Path $InstDir 'nodejs\node.exe'
$lines = @(
  '@echo off',
  ':: generated by ZhiShi (bundled node baked, 1.2.10)',
  ('"' + $node + '" "%~dp0zhishi" %*'),
  'exit /b %ERRORLEVEL%'
)
[System.IO.File]::WriteAllText((Join-Path $bin 'zhishi.cmd'), [string]::Join("`r`n", $lines) + "`r`n")

$p = [Environment]::GetEnvironmentVariable('Path', 'User')
if (-not $p) { $p = '' }
$changed = $false
if (($p -split ';') -notcontains $bin) {
  $newPath = ($p.TrimEnd(';') + ';' + $bin).TrimStart(';')
  [Environment]::SetEnvironmentVariable('Path', $newPath, 'User')
  $changed = $true
}

if ($changed) {
  # Broadcast WM_SETTINGCHANGE so new processes spawned from Explorer pick up PATH.
  if (-not ('Win32.Native' -as [type])) {
    Add-Type -Namespace Win32 -Name Native -MemberDefinition '[System.Runtime.InteropServices.DllImport("user32.dll", SetLastError = true, CharSet = System.Runtime.InteropServices.CharSet.Auto)] public static extern System.IntPtr SendMessageTimeout(System.IntPtr hWnd, uint Msg, System.UIntPtr wParam, string lParam, uint fuFlags, uint uTimeout, out System.UIntPtr lpdwResult);'
  }
  $result = [System.UIntPtr]::Zero
  [Win32.Native]::SendMessageTimeout([System.IntPtr]0xffff, 0x1A, [System.UIntPtr]::Zero, 'Environment', 2, 5000, [ref]$result) | Out-Null
}
Write-Host "zhishi CLI installed to $bin"
