//! CLI install mirror (1.2.3 恢复,1.3.9 从 tui_launcher 拆分——TUI 退役后
//! 保留的唯一职责)。
//!
//! 1.3.9 TUI 退役：原 tui_launcher 的三入口「弹 TUI 终端」职责删除,三入口
//! (启动/二次实例/托盘)改聚焦 GUI 主窗口(见 lib.rs/tray.rs)。本模块只保留
//! [`sync_cli_resources`]——镜像 `resources/cli/` 进 `<data-dir>/bin/`,让
//! `zhishi` 命令在新机器上存在(CLI 子命令与 `zhishi term` 链路独立存活)。

use std::path::{Path, PathBuf};

use tauri::{AppHandle, Manager, Runtime};

use crate::app_dirs;
use crate::sidecar;
use crate::{ulog_error, ulog_info, ulog_warn};

/// Files mirrored from `resources/cli/` into `<data-dir>/bin/`.
/// (`source name in resources`, `installed name`).
///
/// `zhishi.js` installs as the extensionless `zhishi`: on Unix the file IS
/// the `zhishi` command (shebang `#!/usr/bin/env node`). `package.json`
/// (`{"type":"module"}`) must sit next to it so Node treats the extensionless
/// file as ESM (1.2.3 #5 switched the bundle to ESM). On Windows the
/// `zhishi.cmd` entry is **generated** (bundled node path baked, see
/// cli_cmd_content) rather than copied — 1.2.10 puts bin on the user PATH,
/// so the wrapper cannot rely on finding node via PATH.
const CLI_FILES: &[(&str, &str)] = &[
    ("zhishi.js", "zhishi"),
    ("zhishi.cmd", "zhishi.cmd"),
    ("package.json", "package.json"),
];

/// Generate zhishi.cmd with the bundled node's absolute path baked in
/// (1.2.10 — zhishi on PATH): the CLI must work from a bare user-PATH entry
/// on machines without their own Node.js. Content must stay byte-identical
/// with src-tauri/nsis/install-cli.ps1 (install-time drop) — the mirror is
/// content-compared, drift would cause a one-time rewrite on next launch.
#[cfg(windows)]
fn cli_cmd_content(resource_dir: &Path) -> String {
    let node = resource_dir.join("nodejs").join("node.exe");
    format!(
        "@echo off\r\n:: generated by ZhiShi (bundled node baked, 1.2.10)\r\n\"{}\" \"%~dp0zhishi\" %*\r\nexit /b %ERRORLEVEL%\r\n",
        node.display()
    )
}

/// Mirror `resources/cli/` into `<data-dir>/bin/`, skipping files whose
/// content already matches. Idempotent; safe to call on every launch.
///
/// Chosen over self-healing inside `cli::find_cli_script`: that path runs
/// pre-Tauri (no `AppHandle`, no reliable dev-mode `resource_dir`), while
/// `setup()` has both. cli.rs keeps its "launch the app once" error hint.
pub fn sync_cli_resources<R: Runtime>(app: &AppHandle<R>) {
    let resource_dir = match app.path().resource_dir() {
        Ok(dir) => sidecar::normalize_external_path(dir),
        Err(e) => {
            ulog_warn!("[cli-launcher] resource_dir() failed, CLI sync skipped: {}", e);
            return;
        }
    };
    let src_dir: PathBuf = resource_dir.join("cli");
    if !src_dir.is_dir() {
        // Dev builds don't copy bundle resources into target/debug — running
        // from the repo uses src/cli directly, so a missing dir is fine.
        ulog_warn!("[cli-launcher] {:?} not found, CLI sync skipped (dev build?)", src_dir);
        return;
    }
    let Some(data_dir) = app_dirs::zhishi_data_dir() else {
        ulog_warn!("[cli-launcher] no data dir, CLI sync skipped");
        return;
    };
    let bin_dir = data_dir.join("bin");
    if let Err(e) = std::fs::create_dir_all(&bin_dir) {
        ulog_error!("[cli-launcher] failed to create {:?}: {}", bin_dir, e);
        return;
    }
    for (src_name, dst_name) in CLI_FILES {
        let dst = bin_dir.join(dst_name);
        // zhishi.cmd 走生成式（烘焙 bundled node 绝对路径,1.2.10 zhishi 入
        // PATH——不读源文件;内容与 NSIS install-cli.ps1 的安装时产物逐字节
        // 一致,content-compare 不 churn）。
        #[cfg(windows)]
        let content: Option<Vec<u8>> = if *dst_name == "zhishi.cmd" {
            Some(cli_cmd_content(&resource_dir).into_bytes())
        } else {
            None
        };
        #[cfg(not(windows))]
        let content: Option<Vec<u8>> = None;
        let content = match content {
            Some(c) => c,
            None => {
                let src = src_dir.join(src_name);
                let Ok(content) = std::fs::read(&src) else {
                    ulog_warn!("[cli-launcher] {:?} unreadable, skipped", src);
                    continue;
                };
                content
            }
        };
        // Content-compare skip: rewriting a ~1.4 MB bundle on every launch
        // would churn Defender scans for nothing.
        if std::fs::read(&dst).map(|old| old == content).unwrap_or(false) {
            continue;
        }
        match std::fs::write(&dst, &content) {
            Ok(()) => ulog_info!("[cli-launcher] installed CLI file {:?}", dst),
            Err(e) => {
                ulog_error!("[cli-launcher] failed to write {:?}: {}", dst, e);
                continue;
            }
        }
        // Unix: the extensionless script is executed directly → needs +x.
        #[cfg(unix)]
        if *dst_name == "zhishi" {
            use std::os::unix::fs::PermissionsExt;
            let _ = std::fs::set_permissions(&dst, std::fs::Permissions::from_mode(0o755));
        }
    }
}
